version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn --cwd front-end install

      - run: yarn --cwd front-end test