version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn --cwd back-end install
      - run: yarn --cwd front-end install

      - run: yarn --cwd back-end test
      - run: yarn --cwd front-end test